### ISSUE TITLE
Why JSON?

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/MathOptFormat#3]
What is(are) the main reason(s) for JSON?

Currently I am a big fan of TOML, and it seems to be the way to pkg3: https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md#configuration

Maybe its even easier to read by parts since JSON's markup seem too strong. Relates to #1

**Comment by odow** [comment]
As an argument against Protocol Buffers: [the Google documentation says](https://developers.google.com/protocol-buffers/docs/techniques)

> Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy.

**Comment by odow** [comment]
Closing because I think we're okay with JSON for the near-term. We can revisit if it becomes a problem.
