### ISSUE TITLE
Support parameters

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptFormat#5]
From Brad Bell of [CppAD](https://coin-or.github.io/CppAD/doc/cppad.htm):

> The CppAD expression trees represent a non-linear function with a set of independent and dependent
variables. In addition they have constant and dynamic parameters. A constant parameter cannot
change. A dynamic parameter that can change, but no derivatives are computed with respect to it. A
variable can change and derivatives are computed w.r.t. it. The dynamic parameters are placed in the
same address space as the constant parameters. The variables are in a separate address space that is
used for all the forward and reverse mode derivatives (starting with order zero).
>
> Do you think  the MathOptFormat will support the representation of
non-linear functions (as described above) as some substructure ?

I believe all we need to do is define:
```
{"head": "parameter", "name": "my_unique_name", "default": 1.0}
```

This is something that will be very useful in some work I am about to propose: how to record parameterized optimization models. Provided the structure remains the same, these parameters would be the ticket.

**Comment by odow** [comment]
Coming back to this because I want to move forward with a stochastic file format and parameters are needed. cc @joaquimg 

In addition, @tomasfmg is exploring parameters in MOI here: https://github.com/tomasfmg/ParametricOptInterface.jl

## Design options

### Option 1: Parameters are just special variables

Pros:
- Easy to implement.
- Logical extension from MOI

Cons:
- Parameters in variable bounds cause problems:
```Julia
model = Model()
@parameter(model, p == 1)
@variable(model, x >= 2 + p)
# really interpreted as
@variable(model, x)
@constraint(model, x - p >= 2)
```
Could work around this by always inferring constraints as variable bounds if possible. 
1. Process all SingleVariable-in-Set constraints
2. If a `ScalarAffineFunction-in-Set` constraint exists with a single (non-parametric) variable with a coefficient of `1.0` and when interpreted as a bound is still valid, then add as a bound. 

#### Option 1a: `Parameter` set

Define a new `Parameter` set. Parameters are just variables with the constraint
```json
{
    "function": {
        "head": "SingleVariable", "variable": "p"
    },
    "set": {
        "head": "Parameter", "default": 1.0
    }
}
```

#### Option 1b: `Parameter` attribute

Define a `parameter_value` attribute:
```json
"variables": [
    {"name": "x"}, 
    {"name": "p", "parameter_value": 1.0}
]
```
Or
```json
"variables": [
    {"head": "variable", "name": "x"}, 
    {"head": "parameter", "name": "p", "default": 1.0}
]
```

## Option 2: Separate parameters

```json
"variables": [{"name": "x"}],
"parameters": [{"name": "p", "default": 1.0}]
```
Ideally, these parameters are then accepted anywhere that a real scalar is accepted.

Pros:
- Explicit.

Cons:
- We don't have a concept for this in MOI.
- When parsing, we have to check if every number is either a number or a struct.
- What is I want to write the following? Can we have expressions of numbers and parameters?
```Julia
model = Model()
@parameter(model, p == 1)
@variable(model, x >= 2 + p)
```

**Comment by odow** [comment]
https://odow.github.io/StochOptFormat/ has taken the view that parameters are just variables. We give a list of the parameters (random variables) in the outer layer of metadata.

**Comment by joaquimg** [comment]
We can probably make this work, with extra code in the future:
```julia
model = Model()
@parameter(model, p == 1)
@variable(model, x >= 2 + p)
```
even in option 1

**Comment by odow** [comment]
I don't think we're going to do this for now. It's a tricky thing to get right.
